// Generated by dia2code
#ifndef __SERVER__H
#define __SERVER__H

#include "server/HttpStatus.h"
#include "server/AbstractService.h"
#include "server/ServiceManager.h"
#include "server/Player.h"
#include "server/Game.h"
#include "server/PlayerService.h"
#include "server/VersionService.h"
#include "server/ServiceException.h"
#endif
