

HEADERS:=$(shell find src -type f -name '*.h')
DIA2CODE_DIR:=./dia2code/dia2code-0.8.7

all: | clean dia2code configure build run

clean:
	@rm -rf bin build ${HEADERS}
	@rm -f $(shell grep -ls '// Generated by dia2code' main.h ${HEADERS})

distclean: clean
	make -C ${DIA2CODE_DIR} distclean

dia2code: ${DIA2CODE_DIR}/dia2code/dia2code

${DIA2CODE_DIR}/dia2code/dia2code: 
	cd ${DIA2CODE_DIR} && ./configure && make

configure:
	@mkdir -p build 
	@cd build && cmake ..

build:
	@make -s -j4 -C build

run:
	./bin/run

test:
	docker build -t plt-initial -f docker/plt-initial .
	docker build -t plt-build -f docker/plt-build .
	./docker/run_docker_x11.sh plt-build

start-kit:
	@tar -czvf ../plt-start-kit.tar.gz *

.PHONY: configure build clean run test start-kit
