// Generated by dia2code
#ifndef RENDER__GAMEOBJECTTILESET__H
#define RENDER__GAMEOBJECTTILESET__H

#include <vector>

namespace render {
  class Tile;
};
namespace state {
  class GameObject;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "state/GameObject.h"
#include "TileSet.h"

namespace render {

  /// class GameObjectTileSet - 
  class GameObjectTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> town;
    std::vector<Tile> barrack;
    std::vector<Tile> turret;
    std::vector<Tile> farm;
    std::vector<Tile> mine;
    std::vector<Tile> archer;
    std::vector<Tile> infantry;
    std::vector<Tile> farmer;
    // Operations
  public:
    BuildingTileSet ();
    bool getCallWidth ();
    bool getCallHeigth ();
    const bool getImageFile ();
    bool getTile (const state::GameObject game_obect);
    // Setters and Getters
  };

};

#endif
