// Generated by dia2code
#ifndef RENDER__GAMEOBJECTLAYER__H
#define RENDER__GAMEOBJECTLAYER__H


namespace state {
  class GameObject;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/GameObject.h"

namespace render {

  /// class GameObjectLayer - 
  class GameObjectLayer : public render::Layer {
    // Associations
    // Attributes
  public:
    const state::GameObject& game_object;
    // Operations
  public:
    GameObjectLayer (const state::GameObject& game_object);
    // Setters and Getters
  };

};

#endif
