// Generated by dia2code
#ifndef RENDER__STATELAYER__H
#define RENDER__STATELAYER__H


namespace state {
  class State;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/State.h"

namespace render {

  /// class StateLayer - 
  class StateLayer : public render::Layer {
    // Associations
    // Attributes
  public:
    const state::State& state;
    unsigned int current_player;
    unsigned int day_count;
    // Operations
  public:
    StateLayer (const state::State& state);
    bool initSurface ();
    // Setters and Getters
  };

};

#endif
