// Generated by dia2code
#ifndef RENDER__STATETILESET__H
#define RENDER__STATETILESET__H


namespace render {
  class TileSet;
};
namespace state {
  class State;
}

#include "TileSet.h"
#include "state/State.h"

namespace render {

  /// class StateTileSet - 
  class StateTileSet : public render::TileSet {
    // Operations
  public:
    StateTileSet ();
    bool getCellWidth ();
    bool getCellHeight ();
    const bool  getImageFile ();
    bool getTile (char info);
    // Setters and Getters
  };

};

#endif
