// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class VertexArray;
  class Texture;
};
namespace render {
  class Tile;
};
namespace sf {
  class Drawable;
  class Transformable;
}


namespace render {

  /// class Surface - 
  class Surface : public sf::Drawable, public sf::Transformable {
    // Attributes
  private:
    sf::VertexArray squads;
    sf::Texture texture;
    // Operations
  public:
    bool loadTexture (const std::string& image_file);
    bool initQuads (int count);
    bool setSpriteLocation (int i, int x, int y);
    bool setSpriteTexture (int i, const Tile& text);
    bool const draw (sf::RenderTarget& target, sf::RenderStates states);
    // Setters and Getters
  };

};

#endif
