// Generated by dia2code
#ifndef RENDER__TERRAINTILESET__H
#define RENDER__TERRAINTILESET__H

#include <vector>

namespace render {
  class Tile;
};
namespace state {
  class Terrain;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "state/Terrain.h"
#include "TileSet.h"

namespace render {

  /// class TerrainTileSet - 
  class TerrainTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> Moutain;
    std::vector<Tile> forest;
    std::vector<Tile> water;
    std::vector<Tile> grassland;
    std::vector<Tile> swamp;
    // Operations
  public:
    TerrainTileSet ();
    bool getCellWidth ();
    bool getCellHeight ();
    const bool  getImageFile ();
    bool getTile (const state::Terrain terrain_tile);
    // Setters and Getters
  };

};

#endif
