// Generated by dia2code
#ifndef RENDER__TERRAINLAYER__H
#define RENDER__TERRAINLAYER__H


namespace state {
  class Terrain;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/Terrain.h"

namespace render {

  /// class TerrainLayer - 
  class TerrainLayer : public render::Layer {
    // Associations
    // Attributes
  public:
    const state::Terrain& terrain;
    // Operations
  public:
    TerrainLayer (const state::Terrain& terrain);
    // Setters and Getters
  };

};

#endif
