// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H


namespace render {
  class Tile;
}

#include "Tile.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Operations
  public:
    ~TileSet ();
    bool getCellWidth ();
    bool getCellHeight ();
    const bool  getImageFile ();
    virtual bool getTile ();
    // Setters and Getters
  };

};

#endif
