// Generated by dia2code
#ifndef SERVER__HTTPSTATUS__H
#define SERVER__HTTPSTATUS__H


namespace server {

  enum HttpStatus {
    OK     = 200,
    CREATED     = 201,
    NO_CONTENT     = 204,
    BAD_REQUEST     = 400,
    NOT_FOUND     = 404,
    SERVER_ERROR     = 500,
    NOT_IMPLEMENTED     = 501,
    OUT_OF_RESOURCES     = 503
  };

};

#endif
