// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H

#include <memory>
#include <mutex>

namespace ai {
  class AI;
};
namespace render {
  class DrawManager;
};
namespace engine {
  class engine;
}

#include "ai/AI.h"
#include "render/DrawManager.h"
#include "engine/engine.h"

namespace client {

  /// class Client - 
  class Client {
    // Associations
    // Attributes
  private:
    engine::Engine engine;
    std::shared_ptr<ai::AI> npc1_ai;
    std::shared_ptr<ai::AI> npc2_ai;
    mutable std::mutex draw_mutex;
    // Operations
  public:
    Client ();
    bool engineUpdating ();
    bool engineUpdated ();
    bool run ();
    // Setters and Getters
  };

};

#endif
